### PR TITLE
Try to fix frame index issue + no more outframes_dir

### PR DESCRIPTION
**Pull request by Firepal**
In response to #62:
- The "+1" used for compensating for frame filenames is now in `VideoHandlerDisk` instead of `build_output_video`
- Frame index assert now reports more information
- Removed the "outframes" directory mechanism, now STAMMER pipes frames directly to `ffmpeg` for video encoding

### CODE REVIEW

**Comment by Hmlerr** [comment]
Ooh! Ooh! I updated my stammer directory with the changes in this fork and it solved my problem! It works now! Thank you! :D

**Comment by Firepal** [comment]
@Hmlerr This is wonderful news! I don't have enough hard drive space to test this with a big movie, so thank you for testing.
Now we wait for @ArdenButterfield's input. :]

**Comment by Hmlerr** [comment]
@Firepal Here are some videos I created using it. hehehe :D
[https://youtu.be/Ff9_v-UE6xY](https://youtu.be/Ff9_v-UE6xY)
[https://youtu.be/aMPRJaqZf1A](https://youtu.be/aMPRJaqZf1A)

**Comment by ArdenButterfield** [comment]
This is excellent! Thank you so much, @Firepal. And @Hmlerr , your videos are hilarious.

**Pull request merged**
